name: dd-multitool
services:
    api:
        restart: unless-stopped
        image: dd-multitool-api:latest
        environment:
            - PORT=2000
        networks:
            - dundef-tool
    web:
        restart: unless-stopped
        image: dd-multitool-web:latest
        environment:
            - SHARED_ENDPOINT=http://api:2000/
            - DDMT_WEB_CLIENT_ID=${DDMT_WEB_CLIENT_ID}
            - DDMT_WEB_CLIENT_SECRET=${DDMT_WEB_CLIENT_SECRET}
            - AUTH_SECRET=${AUTH_SECRET}
            - AUTH_TRUST_HOST=true
            - AUTH_URL=https://ddmt.overflow.fun

        networks:
            - dundef-tool
        depends_on:
            - api
        ports:
            - "8080:4321"
        healthcheck:
            test: curl --fail http://localhost:4321/ || exit 1
            interval: 30s
            timeout: 5s
            retries: 3
    bot:
        restart: unless-stopped
        image: dd-multitool-bot:latest
        environment:
            - TOKEN=${TOKEN}
            - PREFIX=${PREFIX}
            - SHARED_ENDPOINT=http://api:2000/
        networks:
            - dundef-tool
        depends_on:
            - api


networks:
    dundef-tool: