name: dd-multitool
services:
    api:
        restart: unless-stopped
        image: dd-multitool-api:latest
        environment:
            - PORT=2000
            - DATABASE_PATH=/opt/
        volumes:
            - /opt/api/database:/opt
        networks:
            - dundef-tool
    web:
        restart: unless-stopped
        image: dd-multitool-web:latest
        environment:
            - SHARED_ENDPOINT=http://api:2000/
            - AUTH_DISCORD_ID=${AUTH_DISCORD_ID}
            - AUTH_DISCORD_SECRET=${AUTH_DISCORD_SECRET}
            - AUTH_SECRET=${AUTH_SECRET}
            - AUTH_TRUST_HOST=true
            - AUTH_URL=https://ddmt.overflow.fun
        networks:
            - dundef-tool
        depends_on:
            - api
        ports:
            - "8080:4321"
    bot:
        restart: unless-stopped
        image: dd-multitool-bot:latest
        environment:
            - TOKEN=${TOKEN}
            - PREFIX=${PREFIX}
            - SHARED_ENDPOINT=http://api:2000/
            - ANALYTICS_ENDPOINT=http://analytics:2000/
        networks:
            - dundef-tool
        depends_on:
            - api
    analytics:
        restart: unless-stopped
        image: dd-multitool-analytics:latest
        environment:
            - ANALYTICS_TOKEN=${ANALYTICS_TOKEN}
            - ANALYTICS_PREFIX=${ANALYTICS_PREFIX}
            - ANALYTICS_LOG_CHANNEL_ID=${ANALYTICS_LOG_CHANNEL_ID}
            - PORT=2000
        networks:
            - dundef-tool

networks:
    dundef-tool:
