name: dd-multitool
services:
    api:
        restart: unless-stopped
        image: dd-multitool-api:latest
        environment:
            - PORT=2000
        networks:
            - dundef-tool
    web:
        restart: unless-stopped
        image: dd-multitool-web:latest
        environment:
            - SHARED_ENDPOINT=http://api:2000/
        networks:
            - dundef-tool
        depends_on:
            - api
        ports:
            - "8080:4321"
    web-healthcheck:
        test: curl --fail http://localhost:8080/ || exit 1
        interval: 30s
        timeout: 5s
        retries: 3
    bot:
        restart: unless-stopped
        image: dd-multitool-bot:latest
        environment:
            - TOKEN=${TOKEN}
            - PREFIX=${PREFIX}
            - SHARED_ENDPOINT=http://api:2000/
        networks:
            - dundef-tool
        depends_on:
            - api


networks:
    dundef-tool: