name: Test, build and deploy to production

on:
    push:
        branches:
            - main

jobs:
    test-api:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Check commit message for skiptests
              id: skip_check
              run: |
                  echo "Checking commit message..."
                  LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
                  echo "Last commit message: $LAST_COMMIT_MSG"
                  if [[ "$LAST_COMMIT_MSG" == *"skiptests"* ]]; then
                    echo "skip=true" >> $GITHUB_OUTPUT
                  else
                    echo "skip=false" >> $GITHUB_OUTPUT
                  fi

            - name: Skip tests if commit contains skiptests
              if: steps.skip_check.outputs.skip == 'true'
              run: |
                  echo "Skipping tests due to commit message containing 'skiptests'"
                  exit 0

            - name: Setup Node
              if: steps.skip_check.outputs.skip != 'true'
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install API dependencies
              if: steps.skip_check.outputs.skip != 'true'
              working-directory: ./api
              run: npm install

            - name: Run API tests
              if: steps.skip_check.outputs.skip != 'true'
              working-directory: ./api
              run: npm test

    build-and-deploy:
        runs-on: ubuntu-latest
        needs: test-api
        env:
            TOKEN: ${{ secrets.TOKEN }}
            PREFIX: ${{ secrets.PREFIX }}
            AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
            DDMT_WEB_CLIENT_ID: ${{ secrets.DDMT_WEB_CLIENT_ID }}
            DDMT_WEB_CLIENT_SECRET: ${{ secrets.DDMT_WEB_CLIENT_SECRET }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2

            - name: Build containers
              run: bash ./containers-build.sh

            - name: Restart changed containers
              if: success()
              run: |
                  if [ -f changed_services.txt ]; then
                    for service in $(cat changed_services.txt); do
                      echo "Restarting $service..."
                      docker compose up -d --force-recreate $service
                    done
                  else
                    echo "No containers need restarting."
                  fi

            - name: Cleanup old images
              run: docker image prune -f
